### ISSUE TITLE
[BUG] Production

### ISSUE THREAD

**Issue by sajmon094** [NosAdventure/bugs-reports#1]
It's not possible to produce Refined Gold Necklace cause i can't choose anything to produce 
**Describe the bug**

^

**To Reproduce**
1. Go to 'Inventory Main'
2. Click on 'Production Tools for Adventurers'
3. Scroll down to ''
4. See can't choose anything to produce

**Expected behavior**
Add a Refined Gold Necklace to produce

**Screenshots | GIF**
If applicable, add screenshots or a GIF to help explain your problem.
![image](https://user-images.githubusercontent.com/86253629/122801477-73040b80-d2c4-11eb-8f1a-c1f110ba5b72.png)

**Comment by Worldie1** [comment]
And for the other items, is there recipes ?

**Comment by sajmon094** [comment]
> And for the other items, is there recipes ?

Nope

**Comment by Worldie1** [comment]
So, after investigation, all the items being recipes are bugged and do not display the RecipesItems. (Even if they are parsed)

Thank you for your report @sajmon094

**Comment by Erwann9875** [comment]
Seems to be fixed too.
