### ISSUE TITLE
[BUG] Go to Arena skills doesn't work anymore

### ISSUE THREAD

**Issue by Worldie1** [NosAdventure/bugs-reports#11]
**Describe the bug**
The teleporter skill to go in arena doesn't work anymore ![image](https://user-images.githubusercontent.com/38684155/122848707-686c6500-d30a-11eb-90de-344dec3cf1bf.png)

**To Reproduce**
1. Go to skill tab
2. Click on ![image](https://user-images.githubusercontent.com/38684155/122848707-686c6500-d30a-11eb-90de-344dec3cf1bf.png)
3. Choose the dialog arena teleport for 500 golds or the other one for 1k golds

**Expected behavior**
The player should be teleported in arena

**Other information**

The world display this message : 
`NRun Handler not found: 0 `
when i try to go in the arena with the skill

**Screenshots | GIF**
https://gyazo.com/f6bcbdff2a0c67b785dbae4f73941359

**Comment by 0Lucifer0** [comment]
@Worldie1 need test on the new branch but should be fixed

**Comment by Worldie1** [comment]
It work
