### ISSUE TITLE
[BUG] JobLvl Command

### ISSUE THREAD

**Issue by sajmon094** [NosAdventure/bugs-reports#12]
**Describe the bug**
When u type in chat $JLvl u got message : New skill learned and the job is still the same
^
**To Reproduce**

**Expected behavior**
Command should give job instead of getting new skill.
**Screenshots | GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Comment by Erwann9875** [comment]
Have been fixed by Lucifer

**Comment by sajmon094** [comment]
Now it says wrong value 
![image](https://user-images.githubusercontent.com/86253629/123856527-7e3ce400-d921-11eb-9127-8307fee97beb.png)

**Comment by Erwann9875** [comment]
Not a bug, that's because you're class 0 and you're trying to set a joblevel > to 20

**Comment by sajmon094** [comment]
Yeah, my bad sorry for that

**Comment by Erwann9875** [comment]
No problem, thanks for ur contribution anyway
