### ISSUE TITLE
[BUG] Fragrant Grass

### ISSUE THREAD

**Issue by sajmon094** [NosAdventure/bugs-reports#3]
When you bringing out the grass nothing happens / doesn't get grass into inventory and there is no any message
**Describe the bug**
Fragrant Grass does not drop to inventory  
**To Reproduce**
1. Go to 'NosVille Meadows'
2. Click on 'Fragrant Grass'
4. See fragrant grass doesnt drop to inv

**Expected behavior**
possible to drop grass to the inventory / mission
**Screenshots | GIF**
https://gyazo.com/b29eda1912812cdeb766c56d6e0ab688
If applicable, add screenshots or a GIF to help explain your problem.

**Comment by 0Lucifer0** [comment]
@Worldie1 need test on the new branch but should be fixed

**Comment by Worldie1** [comment]
It work
