### ISSUE TITLE
[BUG] NosBasar

### ISSUE THREAD

**Issue by sajmon094** [NosAdventure/bugs-reports#4]
Entering to NosBasar causing dc
**Describe the bug**

NosBasar causes dc

**To Reproduce**
1. Go to 'Market Place'
2. Click on 'Bibi Basar'
4. See dc

**Expected behavior**
Repair Basar not to cause dc

**Screenshots | GIF**
If applicable, add screenshots or a GIF to help explain your problem.
https://gyazo.com/6bbf8089d68de7a90757472326c4b76b

**Comment by Erwann9875** [comment]
Fixed.
