### ISSUE TITLE
[BUG] Bank

### ISSUE THREAD

**Issue by sajmon094** [NosAdventure/bugs-reports#5]
Deposit to bank is not working
**Describe the bug**
When i want deposit or withdraw money from bank nothing happens
**To Reproduce**
1. Go to 'Cuarry Bank'
2. Click on 'Cuarry Bank Representative'
4. See Deposit then deposit money and nothing happens

**Expected behavior**
Repair bank to be able to deposit money

**Screenshots | GIF**
If applicable, add screenshots or a GIF to help explain your problem.
https://gyazo.com/571056215f08f61e63ce059863c7ad38

**Comment by 0Lucifer0** [comment]
@Worldie1 need test on the new branch but should be fixed

**Comment by Worldie1** [comment]
It work
