### ISSUE TITLE
[BUG] Mate trainer

### ISSUE THREAD

**Issue by sajmon094** [NosAdventure/bugs-reports#6]
NosMate Trainer not appear when used.
**Describe the bug**
^

**To Reproduce**
1. Go to 'Miniland'
2. Click on 'NosMate Trainer'
4. See when use trainer the bushi trainer not appear

**Expected behavior**
Summon bushi while used trainer.

**Screenshots | GIF**
If applicable, add screenshots or a GIF to help explain your problem.
https://gyazo.com/4b65dd3809c80f48ccd4117ec32a62d9

**Comment by Erwann9875** [comment]
Already fixed some times ago ^^'
