### ISSUE TITLE
[BUG] Delay EXP gain and drop when kill monsters

### ISSUE THREAD

**Issue by Worldie1** [NosAdventure/bugs-reports#7]
**Describe the bug**
There is a delay of 1-2s (depend sometimes) to see the exp that we gain or that the message level up appear etc when we killed a monster

**To Reproduce**
1. Kill a monster

**Expected behavior**
Before, when we killed a monster we directly saw our exp updated, and the drop there was no any delay like now

**Screenshots | GIF**
https://gyazo.com/68c8e5366b3e7ad3610cbad4b7ffcd69

**Comment by Erwann9875** [comment]
Seems to be fixed aswell
