### ISSUE TITLE
[BUG] Monsters never stop following us

### ISSUE THREAD

**Issue by Worldie1** [NosAdventure/bugs-reports#8]
**Describe the bug**
When i attack a monster, and get away from him, he still follow me until i kill him. When he kill me, and i revive, he continue to hit me.

**To Reproduce**
1. Attack a monster
2. See error

**Expected behavior**
When i die and revive, the mob is not supposed to continue hit me.

**Screenshots | GIF**
https://gyazo.com/b4e9ed56c4cb5e167a3080a8737e7390

https://gyazo.com/98da2ab4690e60f486ba55f88eaac90d

**Comment by Erwann9875** [comment]
Duplicated of https://github.com/NosAdventure/Source/issues/223
