### ISSUE TITLE
[BUG] Can't delete item from inventory

### ISSUE THREAD

**Issue by Worldie1** [NosAdventure/bugs-reports#9]
**Describe the bug**
We you place an item on the trash bin the msg box appear all time and it doesn't delete the item

**To Reproduce**
1. Go to inventory
2. Place an item on the trash bin
3. See error

**Expected behavior**
It should just delete the item when you press on the button confirm from the msg box

**Screenshots | GIF**
https://gyazo.com/7daa811f1ebd029e349ecf5c47172075

**Comment by 0Lucifer0** [comment]
fixed
